---
- name: Network Playbook
  hosts: dhcp
  become: yes

  tasks:

  - debug:
      msg:
      - "Updating IP of the host at : {{ ansible_host }}"
      - "Setting new IP: {{ new_IP }} of the host at : {{ ansible_host }}"

  - interfaces_file:
      dest: "{{ interface_file}}"
      iface: "{{net_interface}}"
      option: address
      value: '{{ new_IP }}'
      backup: yes
      state: present

  - name: Flushing Interface
    shell: nohup sh -c 'sleep 5; ip addr flush "{{net_interface}}"; systemctl restart networking' &
    become: yes
